package report

import (
    "fmt"
    "strings"
    "github.com/captMcGoose/costguard/internal/pricing"
    "github.com/captMcGoose/costguard/internal/terraform"
)

func GenerateMarkdownReport(changes []terraform.ResourceChange, summary pricing.CostSummary) string {
    var b strings.Builder
    b.WriteString("## 💰 CostGuard Estimate\n\n")
    sign := "+"
    total := summary.TotalMonthly
    if total < 0 {
        sign = "-"
        total = -total
    }
    b.WriteString(fmt.Sprintf("Estimated Monthly Cost Impact: **%s$%.0f/month**\n\n", sign, total))
    b.WriteString("### Top Cost Drivers\n\n")

    if len(summary.Drivers) == 0 {
        b.WriteString("No supported resources priced.\n\n")
    } else {
        b.WriteString("| Resource | Monthly Cost |\n")
        b.WriteString("|----------|--------------|\n")
        for _, d := range summary.Drivers {
            b.WriteString(fmt.Sprintf("| %s | $%.0f |\n", d.Address, d.MonthlyCost))
        }
        b.WriteString("\n")
    }
    b.WriteString("⚠️ Estimate based on supported AWS resources only.\n")
    b.WriteString(fmt.Sprintf("\nGenerated by CostGuard %s\n", "v1.0.0"))
    return b.String()
}
